name: test
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - swift:5.2-xenial
          - swift:5.3-bionic
          - swift:5.4-focal
          - swift:5.5-centos8
    container: ${{ matrix.image }}
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery --sanitize=thread
  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift test --sanitize=thread
